require 'settings'
require 'ui'
require 'packer-config'
require 'neo-tree-config'
require 'mappings'
require 'lsp'
require 'autocmds'
require 'treesitter-config'
require 'toggleterm-config'
require 'telescope-config'
-- require 'colorpicker'
